services:
    app:
        container_name: ydh-myydh-crud-api
        build:
            context: .
        env_file: .env
        ports:
            - 127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}
