name: Check Markdown for Broken Links

on:
    schedule:
        # 01:30 every day
        - cron: "30 1 * * *"
    # Allows this workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    link-check:
        name: Link Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: JustinBeckwith/linkinator-action@v1.5.4
              with:
                  concurrency: 1
                  linksToSkip: "https://github.com/Fdawgs/.*/issues/, https://github.com/Fdawgs/.*/commit/, http://0.0.0.0, http://localhost"
